# Generated by Django 5.1.3 on 2025-02-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutikApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
