# Generated by Django 5.1.3 on 2025-03-04 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutikApp', '0002_alter_vente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recu',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='BoutikApp.vente'),
        ),
    ]
