# Generated by Django 5.1.3 on 2025-03-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoutikApp', '0003_alter_recu_vente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
